name: STEGG_all
channels:
  - bioconda/label/cf201901
  - bioconda
  - conda-forge
  - salilab
  - nodefaults
dependencies:
  - python=3.9
  - anarci
  - biopandas
  - biopython
  - hmmer
  - mdtraj
  - mgltools
  - mkl
  - mmseqs2
  - modeller
  - mpire
  - openmm
  - openmmforcefields
  - pandas
  - pdb-tools
  - pdbfixer
  - pymol-open-source
  - scikit-learn
  - scipy
  - smina
  - tabulate
  - tqdm
  - cmake
  - freesasa
  - ambertools=22
  - pip

  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch
      - deepspeed
      - absl-py
      - dm-tree
      - haddock3
      - ml-collections
      - mol-kit
      - termcolor
