name: STEGG_all
channels:
  - bioconda/label/cf201901
  - bioconda
  - conda-forge
  - salilab
  - nodefaults
dependencies:
  - python=3.9
  - anarci
  - biopandas
  - biopython
  - hmmer
  - mdtraj
  - mgltools
  - mkl
  - mmseqs2
  - modeller
  - mpire
  - openmm
  - openmmforcefields
  - pandas
  - pdb-tools
  - pdbfixer
  - pymol-open-source
  - scikit-learn
  - scipy
  - smina
  - tabulate
  - tqdm
  - pip:
      - absl-py
      - cmake
      - deepspeed
      - dm-tree
      - freesasa
      - haddock3
      - ml-collections
      - mmpbsa-py
      - mol-kit
      - numpy
      - pdb2sql
      - pdb4amber
      - pytraj
      - sander
      - termcolor
      - torch
      - triton
